### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by johnSamilin** [johnSamilin/rosplata#25]
1. Add switch to settings page
2. Add setting for automatic dark mode
3. Add automatic dark mode

**Comment by gjuliao** [comment]
Hi @johnSamilin I can help you with it.  Is it still needed, feel free to asign me to it.  Best!

**Comment by johnSamilin** [comment]
Hi @gjuliao!
Thanks, I would greatly appreciate your help!

**Comment by johnSamilin** [comment]
Just add a handler to FeatureDetector that is being called whenever `matchMedia("(prefers-color-scheme: dark)")` changes. That handler should add `dark` class to html tag

**Comment by johnSamilin** [comment]
Hi @gjuliao! Any progress on this one?
